stages:
  - build
  - test

image: voreen/ci-ubuntu-18.04

variables:
  GIT_DEPTH: 1 # Make cloning faster
  DOCKER_DRIVER: overlay2 # use overlayfs
  GIT_SUBMODULE_STRATEGY: 'normal' #fetch test data repository
  RUN_TESTS_AS_USER: 'test_user'
  REPORT_DIR: 'reports'
  TOOLS_DIR: 'voreen/tools'
  COREPROFILE_BUILD_DIR: 'build_coreprofile'
  COMPATPROFILE_BUILD_DIR: 'build_compatibilityprofile'
  TEST_DATA_DIR: 'test-data/voreen-testdata'
  REGRESSION_TEST_UPLOAD_URL: 'https://uni-muenster.sciebo.de/s/YdhJ4czrPsfqPL6'
  #REGRESSION_TEST_UPLOAD_PASSWORD: configured in gitlab
  XVFB_SERVER_ARGS: -screen 0 640x480x24

before_script:
  - export LIBGL_ALWAYS_SOFTWARE="true"
  - export GALLIUM_DRIVER="llvmpipe" #one of softpipe, llvmpipe or swr
  - export GALLIVM_PERF="no_aos_sampling" #force floating point sampling path in llvmpipe
  - export CURRENT_REVISION=$(git rev-parse HEAD)
  - export NOW=$(date +%Y-%m-%d-%H:%M:%S)
  - export IDENTIFIER=${CI_COMMIT_REF_NAME}--${NOW}--${CURRENT_REVISION}--coreprofile

build_compatprofile:
  stage: build
  script:
    - ci/build_compatibilityprofile.sh ${COMPATPROFILE_BUILD_DIR}
  artifacts:
    paths:
    - "${COMPATPROFILE_BUILD_DIR}/bin/*"
    expire_in: 1 day

build_coreprofile:
  stage: build
  script:
    - ci/build_coreprofile.sh ${COREPROFILE_BUILD_DIR}
  artifacts:
    paths:
    - "${COREPROFILE_BUILD_DIR}/bin/*"
    expire_in: 1 day

# Daily builds
build_default:
  stage: build
  script:
    - ci/build_default.sh $(mktmp -d)
  only:
    - schedules

build_no_modules:
  stage: build
  script:
    - ci/build_no_modules.sh $(mktmp -d)
  only:
    - schedules

build_release:
  stage: build
  script:
    - ci/build_release.sh $(mktmp -d)
  only:
    - schedules

build_static_libs:
  stage: build
  script:
    - ci/build_static_libs.sh $(mktmp -d)
  only:
    - schedules

# Tests
serializertest_coreprofile:
  stage: test
  script:
    - ${COREPROFILE_BUILD_DIR}/bin/serializertest --logLevel=debug --logFile=serializer-log.html
  artifacts:
    paths:
    - serializer-log.html
    expire_in: 1 day

descriptiontest_coreprofile:
  stage: test
  script:
    - ${COREPROFILE_BUILD_DIR}/bin/descriptiontest --logLevel=debug --logFile=descriptiontest-log.html
  artifacts:
    paths:
    - descriptiontest-log.html
    expire_in: 1 day

processorcreatetest_coreprofile:
  stage: test
  script:
    - ${COREPROFILE_BUILD_DIR}/bin/processorcreatetest --logLevel=debug --logFile=processorcreatetest-log.html
  artifacts:
    paths:
    - processorcreatetest-log.html
    expire_in: 1 day

processorinittest_coreprofile:
  stage: test
  script:
    - Xvfb ${XVFB_SERVER_ARGS} :98 -ac &
    - export DISPLAY=:98
    - ${COREPROFILE_BUILD_DIR}/bin/processorinittest --logLevel=info --logFile=processorinittest-log.html
  artifacts:
    paths:
    - processorinittest-log.html
    expire_in: 1 day

# octreetest, networkevaluatortest, processornetworktest and volumeorigintest are boost tests and need a "--"
# before specifying application options!
octreetest_coreprofile:
  stage: test
  script:
    - ${COREPROFILE_BUILD_DIR}/bin/octreetest -- --logLevel=debug --datadir ${TEST_DATA_DIR} --logFile=octreetest-log.html
  artifacts:
    paths:
    - octreetest-log.html
    expire_in: 1 day

networkevaluatortest_coreprofile:
  stage: test
  script:
    - ${COREPROFILE_BUILD_DIR}/bin/networkevaluatortest -- --logLevel=debug --logFile=networkevaluatortest-log.html
  artifacts:
    paths:
    - networkevaluatortest-log.html
    expire_in: 1 day

processornetworktest_coreprofile:
  stage: test
  script:
    - ${COREPROFILE_BUILD_DIR}/bin/processornetworktest -- --logLevel=debug --logFile=processornetworktest-log.html
  artifacts:
    paths:
    - processornetworktest-log.html
    expire_in: 1 day

volumeorigintest_coreprofile:
  stage: test
  script:
    - ${COREPROFILE_BUILD_DIR}/bin/volumeorigintest -- --logLevel=debug --logFile=volumeorigintest-log.html
  artifacts:
    paths:
    - volumeorigintest-log.html
    expire_in: 1 day

regressiontest_coreprofile:
  stage: test
  script:
    - mkdir -p ${IDENTIFIER}
    - Xvfb ${XVFB_SERVER_ARGS} :98 -ac &
    - DISPLAY=:98 ${COREPROFILE_BUILD_DIR}/bin/regressiontest --voreentool ${COREPROFILE_BUILD_DIR}/bin/voreentool --datadir ${TEST_DATA_DIR} -t all --htmlReport ${IDENTIFIER}/regressiontest-report.html --splitHtmlReport true --junitReport ${IDENTIFIER}/regressiontest-junit.xml --reportdir ${IDENTIFIER}/regressiontest_files --keepReferenceData --useCaching false --redirectStdOut true --logLevel info --timeout 60 || EXITCODE=$? #save exit code of regressiontest, but do not stop, yet (need to upload results!)
    - ${TOOLS_DIR}/additional/cloudsend.py --password=${REGRESSION_TEST_UPLOAD_PASSWORD} --add-ci-report=${IDENTIFIER} ${IDENTIFIER}
    - mv ${IDENTIFIER}/regressiontest-junit.xml ./ #actifacts session does not have access to IDENTIFIER variable!
    - $(exit $EXITCODE) #propagate regressiontest exit code
  artifacts:
    reports:
      junit: regressiontest-junit.xml
    expire_in: 1 day
