stages:
  - build
  - test

image: voreen/ci-ubuntu-16.04

variables:
  GIT_DEPTH: 1 # Make cloning faster
  DOCKER_DRIVER: overlay2 # use overlayfs
  GIT_SUBMODULE_STRATEGY: 'normal' #fetch test data repository
  RUN_TESTS_AS_USER: 'test_user'
  REPORT_DIR: 'public_asdf'
  COREPROFILE_BUILD_DIR: 'build_coreprofile'
  TEST_DATA_DIR: 'test-data/voreen-testdata'
  XVFB_SERVER_ARGS: -screen 0 640x480x24
  #TEST_DATA_REPOSITORY: 'zivgitlab.uni-muenster.de/voreen-project/voreen-testdata.git'

before_script:
  - export LIBGL_ALWAYS_SOFTWARE="true"

build_coreprofile:
  stage: build
  script:
    #- ci/build_minimal.sh ${COREPROFILE_BUILD_DIR}
    - ci/build_coreprofile.sh ${COREPROFILE_BUILD_DIR}
    #- runuser $RUN_TESTS_AS_USER -c "ci/build_coreprofile.sh ${COREPROFILE_BUILD_DIR}"
    - ping -c 5 deep-force-one || true
    - ping -c 5 10.5.20.80 || true
  artifacts:
    paths:
    - "${COREPROFILE_BUILD_DIR}/bin/*"
    expire_in: 1 day

serializertest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/serializertest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/serializer-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

descriptiontest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/descriptiontest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/descriptiontest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

processorcreatetest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/processorcreatetest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/processorcreatetest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

processorinittest_coreprofile: #probably needs xserver
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - xvfb-run -s ${XVFB_SERVER_ARGS} glxinfo || true
    - Xvfb ${XVFB_SERVER_ARGS} :98 -ac &
    - export DISPLAY=:98
    - glxinfo || true
    - ${COREPROFILE_BUILD_DIR}/bin/processorinittest --logLevel=info --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/processorinittest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

octreetest_coreprofile: #probably need testdata
  stage: test
  script:
    - ls || true
    - ls ${TEST_DATA_DIR} || true
    - ls .. || true
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/octreetest --log_level=test_suite --datadir ${TEST_DATA_DIR} --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/octreetest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

networkevaluatortest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/networkevaluatortest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/networkevaluatortest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

processornetworktest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/processornetworktest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/processornetworktest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

volumeorigintest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/volumeorigintest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/volumeorigintest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

regressiontest_coreprofile:
  stage: test
  script:
    - ls
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ls
    - Xvfb ${XVFB_SERVER_ARGS} :98 -ac &
    - DISPLAY=:98 ${COREPROFILE_BUILD_DIR}/bin/regressiontest --voreentool ${COREPROFILE_BUILD_DIR}/bin/voreentool --datadir ${TEST_DATA_DIR} -t all --htmlReport ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest-report.html --splitHtmlReport true --junitReport ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest-junit.xml --reportdir ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files --keepReferenceData --useCaching false --redirectStdOut true --logLevel info --timeout 60 || true
    - tar czf ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files.tar.gz ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files
    - ls -lh ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files.tar.gz
    - ls ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files/
    - ls ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/
  artifacts:
    paths:
      #- ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files.tar.gz
      #- ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files/*/*/*/*.txt
      #- ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files/*/*/*/*.html
      #- ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files/*/*/*/*/*.txt
      #- ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest_files/*/*/*/*/*.html
    - ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/
      #reports:
      #junit: ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/regressiontest-junit.xml
    expire_in: 1 day

schedule_test:
  stage: build
  only:
    - schedules
  script:
    - echo Schedule ran! > ${REPORT_DIR}
  artifacts:
    paths:
    - ${REPORT_DIR}
