stages:
  - build

image: voreen/ci-ubuntu-16.04:v3

variables:
  GIT_DEPTH: 1 # Make cloning faster
  DOCKER_DRIVER: overlay2 # use overlayfs
  GIT_SUBMODULE_STRATEGY: 'normal' #fetch test data repository
  RUN_TESTS_AS_USER: 'test_user'
  REPORT_DIR: 'reports'
  TOOLS_DIR: 'voreen/tools'
  COREPROFILE_BUILD_DIR: 'build_coreprofile'
  COMPATPROFILE_BUILD_DIR: 'build_compatibilityprofile'
  DEPLOY_INSTALL_DIR: 'build_deploy'
  SPECIAL_DEPLOY_INSTALL_DIR: 'build_special_deploy'
  TEST_DATA_DIR: 'test-data/voreen-testdata'
  REGRESSION_TEST_UPLOAD_URL: 'https://uni-muenster.sciebo.de/s/YdhJ4czrPsfqPL6'
  #REGRESSION_TEST_UPLOAD_PASSWORD: configured in gitlab
  XVFB_SERVER_ARGS: -screen 0 640x480x24
  SNAPSHOT_NAME_UNIX: voreen-src-unix-nightly
  SNAPSHOT_NAME_WIN: voreen-src-win32-nightly

before_script:
  - export LIBGL_ALWAYS_SOFTWARE="true"
  - export GALLIUM_DRIVER="llvmpipe" #one of softpipe, llvmpipe or swr
  - export GALLIVM_PERF="no_aos_sampling" #force floating point sampling path in llvmpipe
  - export CURRENT_REVISION=$(git rev-parse HEAD)
  - export NOW=$(date +%Y-%m-%d-%H:%M:%S)
  - export IDENTIFIER=${CI_COMMIT_REF_NAME}--${NOW}--${CURRENT_REVISION}
  - export IDENTIFIER_COREPROFILE=${IDENTIFIER}--coreprofile
  - export IDENTIFIER_COMPATPROFILE=${IDENTIFIER}--compatibilityprofile
  - export CMAKE_PREFIX_PATH="/usr/local/Qt-5.12.4/lib/cmake/" # Find Qt cmake scripts in docker image
  - export PATH="/usr/local/Qt-5.12.4/bin:$PATH"               # Find qmake in docker image

######################################################################
# Build stage
######################################################################

build_coreprofile:
  stage: build
  script:
    - ci/build_coreprofile.sh ${COREPROFILE_BUILD_DIR}
  artifacts:
    paths:
    - "${COREPROFILE_BUILD_DIR}/bin/*"
    expire_in: 1 day
  except:
    variables:
      - $DEPLOY_ONLY
      - $SPECIAL_DEPLOY_ONLY
