stages:
  - build
  - test

image: voreen/ci-ubuntu-18.04

variables:
  GIT_DEPTH: 1 # Make cloning faster
  DOCKER_DRIVER: overlay2 # use overlayfs
  GIT_SUBMODULE_STRATEGY: 'normal' #fetch test data repository
  RUN_TESTS_AS_USER: 'test_user'
  REPORT_DIR: 'reports'
  TOOLS_DIR: 'voreen/tools'
  COREPROFILE_BUILD_DIR: 'build_coreprofile'
  TEST_DATA_DIR: 'test-data/voreen-testdata'
  REGRESSION_TEST_UPLOAD_URL: 'https://uni-muenster.sciebo.de/s/YdhJ4czrPsfqPL6'
  #REGRESSION_TEST_UPLOAD_PASSWORD: configured in gitlab
  XVFB_SERVER_ARGS: -screen 0 640x480x24

before_script:
  - export LIBGL_ALWAYS_SOFTWARE="true"
  - export GALLIUM_DRIVER="llvmpipe" #one of softpipe, llvmpipe or swr
  - export GALLIVM_PERF="no_aos_sampling" #force floating point sampling path in llvmpipe
  - export CURRENT_REVISION=$(git rev-parse HEAD)
  - export NOW=$(date +%Y-%m-%d-%H:%M:%S)
  - export IDENTIFIER=${CI_COMMIT_REF_NAME}--${NOW}--${CURRENT_REVISION}--coreprofile

build_coreprofile:
  stage: build
  script:
    #- ci/build_minimal.sh ${COREPROFILE_BUILD_DIR}
    - ci/build_coreprofile.sh ${COREPROFILE_BUILD_DIR}
    #- runuser $RUN_TESTS_AS_USER -c "ci/build_coreprofile.sh ${COREPROFILE_BUILD_DIR}"
  artifacts:
    paths:
    - "${COREPROFILE_BUILD_DIR}/bin/*"
    expire_in: 1 day

serializertest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}
    - ${COREPROFILE_BUILD_DIR}/bin/serializertest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/serializer-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

descriptiontest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}
    - ${COREPROFILE_BUILD_DIR}/bin/descriptiontest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/descriptiontest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

processorcreatetest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}
    - ${COREPROFILE_BUILD_DIR}/bin/processorcreatetest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/processorcreatetest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

processorinittest_coreprofile: #probably needs xserver
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}
    - Xvfb ${XVFB_SERVER_ARGS} :98 -ac &
    - export DISPLAY=:98
    - ${COREPROFILE_BUILD_DIR}/bin/processorinittest --logLevel=info --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/processorinittest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

# octreetest, networkevaluatortest, processornetworktest and volumeorigintest are boost tests and need a "--"
# before specifying application options!
octreetest_coreprofile: #probably need testdata
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}
    - ${COREPROFILE_BUILD_DIR}/bin/octreetest -- --logLevel=debug --datadir ${TEST_DATA_DIR} --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/octreetest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

networkevaluatortest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}
    - ${COREPROFILE_BUILD_DIR}/bin/networkevaluatortest -- --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/networkevaluatortest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

processornetworktest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}
    - ${COREPROFILE_BUILD_DIR}/bin/processornetworktest -- --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/processornetworktest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

volumeorigintest_coreprofile:
  stage: test
  script:
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR}
    - ${COREPROFILE_BUILD_DIR}/bin/volumeorigintest -- --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/volumeorigintest-log.html
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 day

regressiontest_coreprofile:
  stage: test
  script:
    - mkdir -p ${IDENTIFIER}
    - Xvfb ${XVFB_SERVER_ARGS} :98 -ac &
    - DISPLAY=:98 ${COREPROFILE_BUILD_DIR}/bin/regressiontest --voreentool ${COREPROFILE_BUILD_DIR}/bin/voreentool --datadir ${TEST_DATA_DIR} -t all --htmlReport ${IDENTIFIER}/regressiontest-report.html --splitHtmlReport true --junitReport ${IDENTIFIER}/regressiontest-junit.xml --reportdir ${IDENTIFIER}/regressiontest_files --keepReferenceData --useCaching false --redirectStdOut true --logLevel info --timeout 60 || EXITCODE=$? #save exit code of regressiontest, but do not stop, yet (need to upload results!)
    - find ${IDENTIFIER}/ -exec ${TOOLS_DIR}/additional/cloudsend.sh {} ${REGRESSION_TEST_UPLOAD_URL} ${REGRESSION_TEST_UPLOAD_PASSWORD} \;
    - mv ${IDENTIFIER}/regressiontest-junit.xml ./ #actifacts session does not have access to IDENTIFIER variable!
    - $(exit $EXITCODE) #propagate regressiontest exit code
  artifacts:
    reports:
      junit: regressiontest-junit.xml
    expire_in: 1 day

schedule_test:
  stage: build
  only:
    - schedules
  script:
    - echo Schedule ran! > ${REPORT_DIR}
  artifacts:
    paths:
    - ${REPORT_DIR}
