stages:
  - build
  - test

image: voreen/ci-ubuntu-16.04

variables:
  RUN_TESTS_AS_USER: 'test_user'
  COREPROFILE_BUILD_DIR: './build_coreprofile'

build_coreprofile:
  stage: build
  script:
    - runuser $RUN_TESTS_AS_USER -c "ci/build_coreprofile.sh"

serializertest_coreprofile:
  stage: test
  script:
    - runuser $RUN_TESTS_AS_USER -c "${COREPROFILE_BUILD_DIR}/bin/serializertest --logLevel=debug"
