stages:
  - build
  - test

image: voreen/ci-ubuntu-16.04

variables:
  RUN_TESTS_AS_USER: 'test_user'
  REPORT_DIR: 'public'
  COREPROFILE_BUILD_DIR: 'build_coreprofile'
  GIT_DEPTH: 1 # Make cloning faster
  DOCKER_DRIVER: overlay2 # use overlayfs

build_coreprofile:
  stage: build
  script:
    - ci/build_minimal.sh ${COREPROFILE_BUILD_DIR}
      #- runuser $RUN_TESTS_AS_USER -c "ci/build_coreprofile.sh ${COREPROFILE_BUILD_DIR}"
  artifacts:
    paths:
    - "${COREPROFILE_BUILD_DIR}/bin/*"
    expire_in: 1 day

serializertest_coreprofile:
  stage: test
  script:
    - ls -l voreen
    - ls -l voreen/data
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/serializertest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/serializer-log.html || true
    - ls -l voreen
    - ls -l voreen/data
    - ls -l voreen/data/tmp
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 week

descriptiontest_coreprofile:
  stage: test
  script:
    - ls -l voreen
    - ls -l voreen/data
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/descriptiontest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/descriptiontest-log.html || true
    - ls -l voreen
    - ls -l voreen/data
    - ls -l voreen/data/tmp
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 week

processorcreatetest_coreprofile:
  stage: test
  script:
    - ls -l voreen
    - ls -l voreen/data
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/processorcreatetest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/processorcreatetest-log.html || true
    - ls -l voreen
    - ls -l voreen/data
    - ls -l voreen/data/tmp
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 week

processorinittest_coreprofile:
  stage: test
  script:
    - ls -l voreen
    - ls -l voreen/data
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/processorinittest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/processorinittest-log.html || true
    - ls -l voreen
    - ls -l voreen/data
    - ls -l voreen/data/tmp
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 week

octreetest_coreprofile:
  stage: test
  script:
    - ls -l voreen
    - ls -l voreen/data
    - mkdir -p ${REPORT_DIR}/${COREPROFILE_BUILD_DIR} || true
    - ${COREPROFILE_BUILD_DIR}/bin/octreetest --logLevel=debug --logFile=${REPORT_DIR}/${COREPROFILE_BUILD_DIR}/octreetest-log.html || true
    - ls -l voreen
    - ls -l voreen/data
    - ls -l voreen/data/tmp
  artifacts:
    paths:
    - "${REPORT_DIR}"
    expire_in: 1 week
