stages:
  - build
  - test

image: voreen/ci-ubuntu-16.04

variables:
  RUN_TESTS_AS_USER: 'test_user'
  COREPROFILE_BUILD_DIR: 'build_coreprofile'

build_coreprofile:
  stage: build
  script:
    - runuser $RUN_TESTS_AS_USER -c "ci/build_minimal.sh ${COREPROFILE_BUILD_DIR}"
      #- runuser $RUN_TESTS_AS_USER -c "ci/build_coreprofile.sh ${COREPROFILE_BUILD_DIR}"
  artifacts:
    paths:
    - "${COREPROFILE_BUILD_DIR}/bin/*"
    expire_in: 1 day

serializertest_coreprofile:
  stage: test
  script:
    - runuser $RUN_TESTS_AS_USER -c "${COREPROFILE_BUILD_DIR}/bin/serializertest --logLevel=debug --logFile=${COREPROFILE_BUILD_DIR}/serializer.log"
  artifacts:
    paths:
    - "{COREPROFILE_BUILD_DIR}/serializer.log"
    expire_in: 1 week

descriptiontest_coreprofile:
  stage: test
  script:
    - runuser $RUN_TESTS_AS_USER -c "${COREPROFILE_BUILD_DIR}/bin/descriptiontest --logLevel=debug --logFile={COREPROFILE_BUILD_DIR}/descriptiontest.log"
  artifacts:
    paths:
    - "{COREPROFILE_BUILD_DIR}/descriptiontest.log"
    expire_in: 1 week

octreetest_coreprofile:
  stage: test
  script:
    - runuser $RUN_TESTS_AS_USER -c "${COREPROFILE_BUILD_DIR}/bin/octreetest --logLevel=debug --logFile={COREPROFILE_BUILD_DIR}/octreetest.log"
  artifacts:
    paths:
    - "{COREPROFILE_BUILD_DIR}/octreetest.log"
    expire_in: 1 week
